version: '3.7'

services:
  mysql:
    container_name: stimedb
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "supersecretpassword123"
      MYSQL_DATABASE: "dbstime"
      MYSQL_USER: "user01"
      MYSQL_PASSWORD: "secretpassword123"
    volumes:
      - "./mysql/database_stime.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 5
