version: '3.7'

services:
    mysql:
        image: mysql:latest
        command:
            - --log-bin-trust-function-creators=1
            - --activate-all-roles-on-login=ON
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "supersecretpassword123"
        volumes:
            - "./database/stime_ddl.sql:/docker-entrypoint-initdb.d/init.sql"
        healthcheck:
            test: mysql --user=op01 --password=pa55w0rd -e 'use dbstime;'
            start_period: 10s
            interval: 5s
            timeout: 5s
            retries: 5

    mysql_triggers:
        image: mysql:latest
        depends_on:
            mysql:
              condition: service_healthy
        volumes:
            - "./database/stime_triggers.sql:/triggers.sql"
        entrypoint: [ "bash", "-c", "mysql -h mysql -P 3306 -u op01 -p'pa55w0rd' -D dbstime --protocol=tcp < /triggers.sql" ]

    adminer:
        image: adminer:latest
        ports:
            - 8000:8080
        depends_on:
            mysql:
              condition: service_healthy
        environment:
            ADMINER_DEFAULT_SERVER: mysql